# 
# Copyright (C) 2020 ArtXIA <https://github.com/artxia>
# <https://github.com/artxia/Action-NotionSite.git>
#

name: Deploy to Pages

on:
#  schedule:
#    - cron: "*/20 * * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:

      - name: Checkout this repo
        uses: actions/checkout@v2
        with:
          path: this_repo

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Build Site
        run: |
          npm i -g notablog
          cd ${GITHUB_WORKSPACE}/this_repo
          notablog generate .
          ls -la

      - name: Deploy to Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          ssh-key: true
          branch: gh-pages
          folder: public
          clean: true
          single-commit: true

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 2
          keep_minimum_runs: 6
